[Copybara Auto Merge] Merge branch whitechapel into partner-android
edgetpu: fix -Wcast-function-type-strict
Building this driver with the newer AOSP Clang 17.0.0 produces the
following error:
private/google-modules/edgetpu/abrolhos/drivers/edgetpu/edgetpu-device-group.c:1007:4:
error: cast from 'int (*)(struct iova_mapping_worker_param *)' to
'edgetpu_async_job_t' (aka 'int (*)(void *)') converts to incompatible
function type [-Werror,-Wcast-function-type-strict]
(edgetpu_async_job_t)edgetpu_map_iova_sgt_worker);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fix this by declaring edgetpu_map_iova_sgt_worker have the correct
signature, cast the parameter in edgetpu_map_iova_sgt_worker, and remove
the function pointer cast.  This warning was added to clang to help
catch CFI failures at compile time rather than runtime.
Bug: 264965700
edgetpu: sync with darwinn-2.0
9364e47c8 edgetpu: Make group required for creating fence
a257e3575 edgetpu: create debugfs symlinks for non-default device names
b25b06c56 Revert "edgetpu: Continue powering up if the block is still on"
5dea12ffd edgetpu: Continue powering up if the block is still on
af318f68d edgetpu: retry and sleep until block down
b4cf36957 edgetpu: Add etdev as private data for syncfences
ede90cae7 edgetpu: usage_stats add cluster reconfigurations counters
77dae3e48 edgetpu: usage_stats: process metrics v2 data
3b2bc8d98 edgetpu: pm: reject power up if thermal suspended
5f19efb5b edgetpu: usage_stats send metrics v2 requests with v1 fallback
52c262671 edgetpu: usage stats: sync additional metrics v2 changes
e5cc5696b edgetpu: Only call .power_up if needed
d06a8f889 edgetpu: Downgrade warning on external mailbox alloc
52fe2ac98 edgetpu: usage stats add field definitions for metrics v2
28bbb7446 edgetpu: usage stats ignore metric fields beyond known size
Bug: 271372136
Bug: 271374892
Bug: 269476405
Bug: 272701322
Bug: 264971968
Bug: 258868303
GitOrigin-RevId: 03a5015bf5a6601295e1967dbbedbe242192c30c
Change-Id: I2fa4b73fd554d559734f8803c7893570ae9fad8d